### ISSUE TITLE
8장 마지막부분에서 에러로그없이 검은화면만 나옵니다.

### ISSUE THREAD

**Issue by soboroach** [jamesnet214/wpf-explorer#2]
[WpfExplorer.zip](https://github.com/user-attachments/files/17709492/WpfExplorer.zip)

확인 부탁드립니다.

**Comment by jamesnet214** [comment]
두 가지 부분에 문제가 있습니다.

#### 첫 번째로:
----
 WpfExplorer.Location 프로젝트의 Generic.xaml에서

```xaml
<ResourceDictionary Source="/WpfExplorer.Location;component/Themes/Units/LocatorTextBox.xaml"/>
<ResourceDictionary Source="/WpfExplorer.Location;component/Themes/Units/LocatorButton.xaml"/>
```

이 부분은 Themes/Units 폴더 경로가 제대로 되어 있지만

![image](https://github.com/user-attachments/assets/14599e11-dd5f-4e93-a6db-2ad4f588ba36)

이미지에서 보듯이 실제 파일의 물리적 경로는 Untis로 되어있습니다. (오타) 이 물리적인 폴더를 Untis에서 Units으로 변경해주시면 됩니다. (자주 있는 흔한 실수죠)

#### 두 번째로:
----
ExplorerViewModel에서 아마도 진행 과정에서 ImportContent 메서드를 도입하는 과정에서 OnLoaded 부분이 제대로 변경되지 않은 것 같습니다.

```
public class ExplorerViewModel : ObservableBase, IViewLoadable
{
    private readonly IContainerProvider _containerProvider;
    private readonly IRegionManager _regionManager;

    public ExplorerViewModel(IContainerProvider containerProvider,
        IRegionManager regionManager)
    {
        _containerProvider = containerProvider;
        _regionManager = regionManager;
    }

    public void OnLoaded(IViewable view)
    {
        //IRegion mainRegion = _regionManager.Regions["MainRegion"];
        //IViewable mainContent = _containerProvider.Resolve<IViewable>("MainContent");

        ImportContent("MainContent", "MainRegion");
        ImportContent("LocationContent", "LocationRegion");
    }

    private void ImportContent(string name, string regionName)
    {
        IViewable content = _containerProvider.Resolve<IViewable>(name);
        IRegion region = _regionManager.Regions[regionName];
        if(!region.Views.Contains(content))
        {
            region.Add(content);
        }
        region.Activate(content);
    }
}
```
OnLoaded를 보시면 mainRegion, mainContent를 각각 할당만 하고 나머지 Contents 로직과 Add, Activate 로직이 ImportContent로 분리된 것을 볼 수 있는데요. 그렇기 때문에 뷰를 Region에 제대로 주입하지 않고 있었던 것입니다.

따라서 다음처럼 ImportContent를 호출하는 메서드를 추가하고 기존 소스코드는 폐기하면 됩니다.

----

변경된 프로젝트도 참고 드립니다.
[WpfExplorer_soboroach.zip](https://github.com/user-attachments/files/17709738/WpfExplorer_soboroach.zip)

문제가 해결되었으면 말씀해주세요. 감사합니다.

**Comment by soboroach** [comment]
잘 됩니다! 감사합니다!!

**Comment by jamesnet214** [comment]
@soboroach 문제가 해결됐으니 이슈 닫겠습니다~
